#name: Deploy to Amazon ECS
#
#on: [ push ]
#
#env:
#  AWS_REGION: eu-central-1
#  AWS_EC2_HOST: ec2-3-70-19-240.eu-central-1.compute.amazonaws.com
#
#jobs:
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    environment: production
#
#    steps:
#      - name: Run docker compose on EC2 via ssh
#        uses: appleboy/ssh-action@v0.1.10
#        with:
#          host: ${{ env.AWS_EC2_HOST }}
#          username: ${{ secrets.AWS_UBUNTU_USER }}
#          key: ${{ secrets.AWS_LOCAL_PK }}
#          script: sudo docker-compose up -d
