name: Deploy to Amazon ECS

on: [ push ]

env:
  AWS_REGION: eu-central-1
  AWS_EC2_HOST: ec2-3-70-19-240.eu-central-1.compute.amazonaws.com

jobs:
  deploy:
    name: Deploy
#    runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    environment: production

    steps:
      - name: Run docker compose
#        uses: actions/checkout@v3
        env:
          PRIVATE_KEY: ${{ secrets.AWS_LOCAL_PK }}
          HOSTNAME: ${{env.AWS_EC2_HOST}}
          USER_NAME: ${secrets.AWS_UBUNTU_USER}
        run: |
          echo "$PRIVATE_KEY" > local.pem && chmod 400 local.pem
          ssh -o StrictHostKeyChecking=no -i local.pem ${USER_NAME}@${HOSTNAME} '
          
          # Now we have got the access of EC2 and we will start the deploy .
          sudo docker-compose up -d
          '
