name: Deploy to Amazon ECS

on: [ push ]

env:
  AWS_REGION: eu-central-1
  AWS_EC2_HOST: 3.70.19.240

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Run docker compose
#        uses: actions/checkout@v3
        env:
          PRIVATE_KEY: ${{ secrets.AWS_LOCAL_PK }}
          HOSTNAME: ${{env.AWS_EC2_HOST}}
          USER_NAME: ${secrets.AWS_UBUNTU_USER}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
          # Now we have got the access of EC2 and we will start the deploy .
          sudo docker-compose up -d
          '


#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ADMIN }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ADMIN }}
#          aws-region: ${{ env.AWS_REGION }}


