name: github ci tests
on:
  release:
    types: [ published ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo "From GITHUB_REF#refs/*/ $RELEASE_VERSION"
          echo "From env.RELEASE_VERSION ${{ env.RELEASE_VERSION }}"
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"